# 개발 환경 설정
aws:
  region: ap-northeast-2
  credentials:
    use-instance-profile: false
    profile-name: default
  client-config:
    connection-timeout: PT5S
    socket-timeout: PT15S
    max-concurrency: 20
    user-agent-prefix: "ryuqq-aws-sdk-dev"
  retry-policy:
    max-retries: 2
    base-delay: PT0.05S
    max-backoff-time: PT5S

# 개발환경 로깅 상세 설정
logging:
  level:
    com.ryuqq.aws: DEBUG
    software.amazon.awssdk: INFO
    software.amazon.awssdk.request: DEBUG
    org.springframework.web: DEBUG
    root: INFO

# LocalStack 설정 (개발 환경)
localstack:
  endpoint: ${LOCALSTACK_ENDPOINT:http://localhost:4566}
  
# H2 Database (개발/테스트용)
spring:
  h2:
    console:
      enabled: true