# Example Application Configuration
spring:
  application:
    name: aws-sdk-example-app
  profiles:
    active: dev

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# AWS SDK Configuration
aws:
  region: us-west-2
  credentials:
    use-instance-profile: false
    profile-name: default

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.ryuqq: DEBUG
    software.amazon.awssdk: WARN
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

aws:
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:4566
  sqs:
    default-queue-url-prefix: http://localhost:4566/000000000000/

logging:
  level:
    com.ryuqq: DEBUG
    software.amazon.awssdk.request: DEBUG

---
# Production Profile  
spring:
  config:
    activate:
      on-profile: prod

aws:
  credentials:
    use-instance-profile: true

logging:
  level:
    com.ryuqq: INFO
    org.springframework: WARN
    software.amazon.awssdk: ERROR