# DynamoDB 기본 설정
# 프로덕션 환경에서의 최적화된 DynamoDB 클라이언트 설정

aws:
  dynamodb:
    # 기본 테이블 설정
    table-prefix: ""
    table-suffix: ""
    enable-point-in-time-recovery: true
    tags:
      Environment: "production"
      Application: "awskit"
      ManagedBy: "spring-boot"
    
    # 클라이언트 설정
    client-config:
      enable-metrics: true
      enable-client-side-monitoring: true
      enable-request-compression: true
      request-compression-threshold-bytes: 10240
      enable-client-caching: true
      cache-key-ttl: PT5M
      enable-request-logging: false
      enable-response-logging: false
      sensitive-headers:
        - "Authorization"
        - "X-Amz-Security-Token"
    
    # 연결 설정
    connection-config:
      max-connections: 50
      connection-timeout: PT10S
      socket-timeout: PT30S
      connection-acquisition-timeout: PT10S
      connection-time-to-live: PT5M
      connection-max-idle-time: PT1M
      tcp-keep-alive: true
      keep-alive-timeout: PT30S
      enable-http2: false
      max-concurrent-streams: 100
    
    # 재시도 설정
    retry-config:
      max-retries: 3
      base-delay: PT0.1S
      max-backoff-time: PT30S
      backoff-strategy: "EXPONENTIAL"
      retryable-error-codes:
        - "ProvisionedThroughputExceededException"
        - "RequestLimitExceeded"
        - "InternalServerError"
        - "ServiceUnavailable"
      enable-adaptive-retry: true
      enable-throttle-retry: true
      throttle-retry-delay: PT0.5S
      enable-circuit-breaker: false
      circuit-breaker-failure-threshold: 5
      circuit-breaker-recovery-timeout: PT1M
    
    # 테이블 설정
    table-config:
      billing-mode: "PAY_PER_REQUEST"
      read-capacity-units: 5
      write-capacity-units: 5
      enable-deletion-protection: true
      enable-streams: false
      stream-view-type: "NEW_AND_OLD_IMAGES"
    
    # 쿼리 설정
    query-config:
      default-page-size: 100
      scan-timeout: PT5M
      query-timeout: PT30S
      consistent-read: false
      enable-parallel-scan: false
      total-segments: 1
    
    # 배치 설정
    batch-config:
      batch-write-size: 25
      batch-read-size: 100
      batch-flush-interval: PT1S
      enable-batching: true
      max-retry-attempts: 3
      retry-delay: PT0.1S
    
    # 용량 관리 설정
    capacity-config:
      enable-auto-scaling: false
      read-min-capacity: 5
      read-max-capacity: 4000
      read-target-utilization: 70
      read-scale-up-cooldown: PT1M
      read-scale-down-cooldown: PT5M
      write-min-capacity: 5
      write-max-capacity: 4000
      write-target-utilization: 70
      write-scale-up-cooldown: PT1M
      write-scale-down-cooldown: PT5M
      enable-rate-limiting: false
      read-requests-per-second: 100
      write-requests-per-second: 100
      bulk-operation-batch-size: 25
      bulk-operation-delay: PT0.1S
    
    # 지역 설정
    region-config:
      region: "us-east-1"
      enable-cross-region-replication: false
      enable-global-tables: false
      use-fips-endpoint: false
      use-dual-stack-endpoint: false
    
    # 모니터링 설정
    monitoring-config:
      enable-cloud-watch-metrics: true
      cloud-watch-namespace: "DynamoDB/ApplicationMetrics"
      metrics-publish-interval: PT1M
      enable-x-ray-tracing: false
      x-ray-tracing-name: "DynamoDB"
      x-ray-sampling-rate: 0.1
      enable-health-check: true
      health-check-interval: PT1M
      health-check-timeout: PT5S
      enable-performance-monitoring: true
      slow-query-threshold: PT1S
      log-slow-queries: true
      enable-alerts: false
      error-rate-threshold: 5
      alert-cooldown: PT5M
      metric-tags:
        Service: "dynamodb-client"
        Version: "1.0.0"

# 로깅 설정
logging:
  level:
    com.ryuqq.aws.dynamodb: INFO
    software.amazon.awssdk.services.dynamodb: WARN
    software.amazon.awssdk.request: WARN