# DynamoDB 개발 환경 설정

aws:
  dynamodb:
    # 개발 환경용 설정 오버라이드
    table-prefix: "dev-"
    enable-point-in-time-recovery: false
    tags:
      Environment: "development"
      Application: "awskit"
      ManagedBy: "spring-boot"
    
    # 클라이언트 설정
    client-config:
      enable-metrics: false
      enable-client-side-monitoring: false
      enable-request-compression: false
      enable-client-caching: false
      enable-request-logging: true
      enable-response-logging: true
    
    # 연결 설정 (개발용 축소)
    connection-config:
      max-connections: 10
      connection-timeout: PT5S
      socket-timeout: PT15S
    
    # 재시도 설정 (개발용 빠른 실패)
    retry-config:
      max-retries: 1
      base-delay: PT0.05S
      max-backoff-time: PT5S
      enable-circuit-breaker: false
    
    # 테이블 설정
    table-config:
      billing-mode: "PAY_PER_REQUEST"
      enable-deletion-protection: false
      enable-streams: true
    
    # 쿼리 설정
    query-config:
      default-page-size: 20
      scan-timeout: PT1M
      query-timeout: PT10S
    
    # 배치 설정
    batch-config:
      batch-write-size: 10
      batch-read-size: 20
      enable-batching: true
    
    # 용량 관리 설정
    capacity-config:
      enable-auto-scaling: false
      enable-rate-limiting: false
    
    # 모니터링 설정
    monitoring-config:
      enable-cloud-watch-metrics: false
      enable-x-ray-tracing: false
      enable-health-check: true
      health-check-interval: PT30S
      enable-performance-monitoring: true
      slow-query-threshold: PT0.5S
      log-slow-queries: true
      enable-alerts: false

# 로깅 설정 (개발용 상세)
logging:
  level:
    com.ryuqq.aws.dynamodb: DEBUG
    software.amazon.awssdk.services.dynamodb: DEBUG
    software.amazon.awssdk.request: WARN